### ISSUE TITLE
Link to app not working

### ISSUE THREAD

**Issue by ajaust** [pro-well-plan/pwptemp-web-app#6]
The link [pwptemp.appspot.com](http://pwptemp.appspot.com/) from the README is not working. Instead, I get the following error message:

```text
Error: Server Error
The server encountered an error and could not complete your request.

Please try again in 30 seconds.
```

Is the repository at [opensource_apps](https://github.com/pro-well-plan/opensource_apps) the successor of this ([pwptemp-web-app](https://github.com/pro-well-plan/pwptemp-web-app)) repository?

**Comment by jcamiloangarita** [comment]
Hi @ajaust, thanks for the observation.

This was an initial app to cover our opensource tool for [wellbore temperature distribution (pwptemp)](https://github.com/pro-well-plan/pwptemp). However, it's not maintained anymore. Instead, we are including all our opensource tools here [repo](https://github.com/pro-well-plan/opensource_apps) / [webapps](https://lnkd.in/g2Yr5B9)

**Comment by ajaust** [comment]
Thanks for the quick response!
